services:
  neo4j:
    image: 'neo4j:5.15'
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
      - 'NEO4J_PLUGINS=["apoc"]'
      - 'NEO4J_dbms_security_procedures_unrestricted=apoc.*'
      - 'NEO4J_dbms_memory_heap_initial__size=512m'
      - 'NEO4J_dbms_memory_heap_max__size=2G'
      - 'NEO4J_dbms_memory_pagecache_size=1G'
      - 'NEO4J_dbms_connector_bolt_listen__address=:7687'
      - 'NEO4J_dbms_connector_http_listen__address=:7474'
    ports:
      - '7687:7687'
      - '7474:7474'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "notverysecret", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
